version: 2
updates:
- package-ecosystem: cargo
  directory: "/rust_wasi_runtime"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: wasmtime-wasi
    versions:
    - 0.22.0
    - 0.24.0
    - 0.25.0
  - dependency-name: wasmtime-jit
    versions:
    - 0.22.0
    - 0.23.0
    - 0.24.0
    - 0.25.0
